# Site settings
title: hamzawinix 
description: "hamzawinix blog"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: hamzawinix 
user_title: hamzawinix - Engineer,Cybersec student
email: hamzawinix@gmail.com
twitter_username: hamzawinix 
github_username: hamzawinix 
gplus_username: hamzawinix 
linkedin_public_url:  # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: hamzawinix 
profile_picture:  ./src/img/zero.jpeg


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: http://www.github.com/hamzawinix
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://www.twitter.com/hamzawinix
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: fluany
    url: https://github.com/fluany/fluany
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
